# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

apt_packages:
  - openjdk-8-jdk
env:
  - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
